stages:
  - test
variables:
  DOCKER_HOST: tcp://docker:2375/

stages:
  - test
  - deploy
  
unittests:
  stage: test
  services:
  - docker:dind
  image: python:3.6-alpine

  before_script:
    - apk add --no-cache --virtual .build-deps gcc musl-dev libffi-dev openssl-dev python3 python3-dev make docker
    - docker info
    - pip3 install .
    - pip3 install -r test-requirements.txt
  script:
    - make unit-tests-with-coverage

image: python:3.7-alpine

pages:
  stage: deploy
  script:
  - pip install -U sphinx recommonmark
  - sphinx-build -b html docs/ public
  artifacts:
    paths:
    - public
  only:
    - master
