variables:
  DOCKER_HOST: tcp://docker:2375/

image: python:3.6-alpine
before_script:
  - apk add --no-cache --virtual .build-deps gcc musl-dev libffi-dev openssl-dev python3 python3-dev make docker
  - docker info

stages:
  - test
  - deploy
  
unittests:
  image: ghcr.io/nicceboy/multipython:latest
  before_script:
    - echo "Current versions:"
    - source ~/.bashrc && echo "Python 3.6: $(python3.6 -V)"
  stage: test
  services:
  - docker:dind
  script:
    - source ~/.bashrc && tox

integrationtests:
  stage: test
  services:
  - docker:dind
  script:
    - make integration-tests



pages:
  stage: deploy
  image: python:3.7-alpine
  before_script:
  - pip install -U sphinx recommonmark
  script:
  - sphinx-build -b html docs/ public
  artifacts:
    paths:
    - public
  only:
    - master

release:
  stage: deploy
  before_script:
    - apk add --no-cache --virtual .build-deps gcc musl-dev libffi-dev openssl-dev python3 python3-dev make
    - pip3 install setuptools wheel twine
  script:
    - export TWINE_USERNAME TWINE_PASSWORD
    - make only-upload
  rules:
    - if: $CI_COMMIT_TAG

