variables:
  DOCKER_HOST: tcp://docker:2375/

image: python:3.6-alpine
before_script:
  - apk add --no-cache --virtual .build-deps gcc musl-dev libffi-dev openssl-dev python3 python3-dev make docker
  - docker info

stages:
  - test
  - deploy
  
unittests:
  # upstream image https://github.com/Nicceboy/tox-with-multipython
  image: ghcr.io/nicceboy/multipython:latest
  before_script:
    # pytest-cov requires sqlite3
    - apt-get update && apt-get install -y libsqlite3-0
    - echo "Current versions:"
    - source ~/.bashrc
    - python3.6 -V
    - python3.7 -V
    - python3.8 -V
    - python3.9 -V
  stage: test
  services:
  - docker:dind
  script:
    - source ~/.bashrc && tox -- --cov=cincan tests

integrationtests:
  stage: test
  services:
  - docker:dind
  script:
    - make integration-tests



pages:
  stage: deploy
  image: python:3.7-alpine
  before_script:
  - pip install -U sphinx recommonmark
  script:
  - sphinx-build -b html docs/ public
  artifacts:
    paths:
    - public
  only:
    - master

release:
  stage: deploy
  before_script:
    - apk add --no-cache --virtual .build-deps gcc musl-dev libffi-dev openssl-dev python3 python3-dev make
    - pip3 install setuptools wheel twine
  script:
    - export $TWINE_USERNAME $TWINE_PASSWORD
    - make only-upload
  rules:
    - if: $CI_COMMIT_TAG

