stages:
  - test

services:
  - docker:dind
  
unittests:
  stage: test
  image: alpine:python3
  before_script:
    - apk add --no-cache --virtual .build-deps gcc musl-dev libffi-dev openssl-dev python3-dev
    - pip3 install .
    - pip3 install -r test-requirements.txt
    # - eval ${docker-machine env default}
  script:
    - pytest