stages:
  - test

unittests:
  stage: test
  image: "python:3-alpine"
  before_script:
    - apk add gcc musl-dev libffi-dev openssl-dev python3-dev --no-cache
    - pip3 install .
    - pip3 install -r test-requirements.txt
  script:
    - pytest