stages:
  - test

unittests:
  stage: test
  image: "docker:dind"
  before_script:
    - apk add gcc musl-dev libffi-dev openssl-dev python3 python3-dev --no-cache
    - pip3 install .
    - pip3 install -r test-requirements.txt
    # - eval ${docker-machine env default}
  script:
    - pytest